os: osx
language: objective-c
osx_image: xcode11
xcode_project: ./EnumKit.xcodeproj
xcode_scheme: EnumKit-Package
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11

after_success:
    - bash <(curl -s https://codecov.io/bash)
